name: Install Node dependencies
description: Installs Node.js and the pnpm dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0

    - name: Install Node.js
      uses: actions/setup-node@v5.0.0

    - name: Install dependencies
      run: pnpm install
      shell: sh
