# SPDX-FileCopyrightText: Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Build artifacts

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE: oci-push.element.io/element-admin

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: "${{ env.IMAGE }}"
          bake-target: docker-metadata-action
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: oci-push.element.io
          username: ${{ secrets.OCI_PUSH_USERNAME }}
          password: ${{ secrets.OCI_PUSH_PASSWORD }}

      - name: Build and push
        id: bake
        uses: docker/bake-action@v6.9.0
        with:
          files: |
            ./docker/docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          set: |
            base.output=type=image,push=true
